// This file is auto-generated by @hey-api/openapi-ts

export {
  type Options,
  processPostcode,
  searchProcessedPostcodes,
} from "./sdk.gen";
export type {
  ClientOptions,
  DictionaryOfStringAndDecimal,
  ListOfEpcAssessmentResponse,
  ListOfPostcodeResponse,
  ProblemDetails,
  ProcessPostcodeData,
  ProcessPostcodeError,
  ProcessPostcodeErrors,
  ProcessPostcodeRequest,
  ProcessPostcodeResponse,
  ProcessPostcodeResponse2,
  ProcessPostcodeResponses,
  SearchProcessedPostcodesData,
  SearchProcessedPostcodesEpcAssessmentAggregationResponse,
  SearchProcessedPostcodesEpcAssessmentResponse,
  SearchProcessedPostcodesError,
  SearchProcessedPostcodesErrors,
  SearchProcessedPostcodesLsoaDeprivationResponse,
  SearchProcessedPostcodesPostcodeResponse,
  SearchProcessedPostcodesRequest,
  SearchProcessedPostcodesResponse,
  SearchProcessedPostcodesResponse2,
  SearchProcessedPostcodesResponses,
} from "./types.gen";
