// This file is auto-generated by @hey-api/openapi-ts

export { type Options, processPostcode } from "./sdk.gen";
export type {
  ClientOptions,
  ProblemDetails,
  ProcessPostcodeData,
  ProcessPostcodeError,
  ProcessPostcodeErrors,
  ProcessPostcodeRequest,
  ProcessPostcodeResponse,
  ProcessPostcodeResponse2,
  ProcessPostcodeResponses,
} from "./types.gen";
