// This file is auto-generated by @hey-api/openapi-ts

export { getPostcodeDeprivation, type Options } from "./sdk.gen";
export type {
  ClientOptions,
  GetPostcodeDeprivationData,
  GetPostcodeDeprivationError,
  GetPostcodeDeprivationErrors,
  GetPostcodeDeprivationPostcodeDeprivationResponse,
  GetPostcodeDeprivationRequest,
  GetPostcodeDeprivationResponse,
  GetPostcodeDeprivationResponse2,
  GetPostcodeDeprivationResponses,
  ProblemDetails,
} from "./types.gen";
