// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:
 * ```app.UseFastEndpoints(c =&gt; c.Errors.UseProblemDetails())```
 */
export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: number;
  instance?: string;
  traceId?: string;
  /**
   * the details of the error
   */
  detail?: null | string;
  errors?: Array<{
    /**
     * the name of the error or property of the dto that caused the error
     */
    name?: string;
    /**
     * the reason for the error
     */
    reason?: string;
    /**
     * the code of the error
     */
    code?: null | string;
    /**
     * the severity of the error
     */
    severity?: null | string;
  }>;
};

export type ProcessPostcodeRequest = {
  postcode: string;
  refreshEPCData?: boolean;
};

export type ProcessPostcodeResponse = {
  postcode: string;
  message: string;
};

export type ProcessPostcodeData = {
  body: ProcessPostcodeRequest;
  path?: never;
  query?: never;
  url: "/api/postcodes/process";
};

export type ProcessPostcodeErrors = {
  /**
   * The requested resource was not found.
   */
  404: ProblemDetails;
  /**
   * Server Error
   */
  500: ProblemDetails;
  /**
   * An upstream service gateway error occurred.
   */
  502: ProblemDetails;
};

export type ProcessPostcodeError =
  ProcessPostcodeErrors[keyof ProcessPostcodeErrors];

export type ProcessPostcodeResponses = {
  /**
   * The request was successful.
   */
  200: ProcessPostcodeResponse;
};

export type ProcessPostcodeResponse2 =
  ProcessPostcodeResponses[keyof ProcessPostcodeResponses];
