// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type EpcCertificate = {
  certificateNumber: string;
  addressLine1: null | string;
  addressLine2: null | string;
  addressLine3: null | string;
  addressLine4: null | string;
  postcode: null | string;
  postTown: null | string;
  council: null | string;
  constituency: null | string;
  currentEnergyEfficiencyBand: null | string;
  registrationDate: null | string;
  uprn: null | number;
  schemaType: null | string;
};

export type GetPostcodeDeprivationPostcodeDeprivationResponse = {
  postcode: string;
  markAsDone: boolean;
  lsoaCode: null | string;
  lsoaName: null | string;
  multipleDeprivationPercentage: null | number;
  multipleDeprivationDecile: null | number;
};

export type GetPostcodeDeprivationRequest = {
  postcode: string;
};

export type GetPostcodeDeprivationResponse = {
  data: GetPostcodeDeprivationPostcodeDeprivationResponse | null;
  epcData: ListOfEpcCertificate | null;
};

export type ListOfEpcCertificate = Array<EpcCertificate>;

/**
 * RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:
 * ```app.UseFastEndpoints(c =&gt; c.Errors.UseProblemDetails())```
 */
export type ProblemDetails = {
  type?: null | string;
  title?: null | string;
  status?: number;
  instance?: string;
  traceId?: string;
  /**
   * the details of the error
   */
  detail?: null | string;
  errors?: Array<{
    /**
     * the name of the error or property of the dto that caused the error
     */
    name?: string;
    /**
     * the reason for the error
     */
    reason?: string;
    /**
     * the code of the error
     */
    code?: null | string;
    /**
     * the severity of the error
     */
    severity?: null | string;
  }>;
};

export type GetPostcodeDeprivationData = {
  body: GetPostcodeDeprivationRequest;
  path?: never;
  query?: never;
  url: "/api/postcodes/lookup";
};

export type GetPostcodeDeprivationErrors = {
  /**
   * The requested resource was not found.
   */
  404: ProblemDetails;
  /**
   * Server Error
   */
  500: ProblemDetails;
  /**
   * An upstream service gateway error occurred.
   */
  502: ProblemDetails;
};

export type GetPostcodeDeprivationError =
  GetPostcodeDeprivationErrors[keyof GetPostcodeDeprivationErrors];

export type GetPostcodeDeprivationResponses = {
  /**
   * The request was successful.
   */
  200: GetPostcodeDeprivationResponse;
};

export type GetPostcodeDeprivationResponse2 =
  GetPostcodeDeprivationResponses[keyof GetPostcodeDeprivationResponses];
