---
name: epc-lead-generator-test
services:
  db:
    image: postgres
    container_name: epc-lead-generator-test-db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes: [./init.sql:/docker-entrypoint-initdb.d/init.sql]
    ports: [5435:5432]
