// This file is auto-generated by @hey-api/openapi-ts
import type { UseMutationOptions } from "@tanstack/react-query";
import { type Options, processPostcode } from "../sdk.gen";
import type {
  ProcessPostcodeData,
  ProcessPostcodeError,
  ProcessPostcodeResponse2,
} from "../types.gen";

export const processPostcodeMutation = (
  options?: Partial<Options<ProcessPostcodeData>>,
): UseMutationOptions<
  ProcessPostcodeResponse2,
  ProcessPostcodeError,
  Options<ProcessPostcodeData>
> => {
  const mutationOptions: UseMutationOptions<
    ProcessPostcodeResponse2,
    ProcessPostcodeError,
    Options<ProcessPostcodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await processPostcode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
