// This file is auto-generated by @hey-api/openapi-ts
import type { UseMutationOptions } from "@tanstack/react-query";
import { type Options, getPostcodeDeprivation } from "../sdk.gen";
import type {
  GetPostcodeDeprivationData,
  GetPostcodeDeprivationError,
  GetPostcodeDeprivationResponse2,
} from "../types.gen";

/**
 * Looks up postcode deprivation data
 */
export const getPostcodeDeprivationMutation = (
  options?: Partial<Options<GetPostcodeDeprivationData>>,
): UseMutationOptions<
  GetPostcodeDeprivationResponse2,
  GetPostcodeDeprivationError,
  Options<GetPostcodeDeprivationData>
> => {
  const mutationOptions: UseMutationOptions<
    GetPostcodeDeprivationResponse2,
    GetPostcodeDeprivationError,
    Options<GetPostcodeDeprivationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await getPostcodeDeprivation({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
