// This file is auto-generated by @hey-api/openapi-ts
import { type UseMutationOptions, queryOptions } from "@tanstack/react-query";
import { client } from "../client.gen";
import {
  type Options,
  processPostcode,
  searchProcessedPostcodes,
} from "../sdk.gen";
import type {
  ProcessPostcodeData,
  ProcessPostcodeError,
  ProcessPostcodeResponse2,
  SearchProcessedPostcodesData,
  SearchProcessedPostcodesError,
  SearchProcessedPostcodesResponse2,
} from "../types.gen";

export const processPostcodeMutation = (
  options?: Partial<Options<ProcessPostcodeData>>,
): UseMutationOptions<
  ProcessPostcodeResponse2,
  ProcessPostcodeError,
  Options<ProcessPostcodeData>
> => {
  const mutationOptions: UseMutationOptions<
    ProcessPostcodeResponse2,
    ProcessPostcodeError,
    Options<ProcessPostcodeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await processPostcode({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const searchProcessedPostcodesQueryKey = (
  options?: Options<SearchProcessedPostcodesData>,
) => createQueryKey("searchProcessedPostcodes", options);

export const searchProcessedPostcodesOptions = (
  options?: Options<SearchProcessedPostcodesData>,
) =>
  queryOptions<
    SearchProcessedPostcodesResponse2,
    SearchProcessedPostcodesError,
    SearchProcessedPostcodesResponse2,
    ReturnType<typeof searchProcessedPostcodesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchProcessedPostcodes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchProcessedPostcodesQueryKey(options),
  });
